-- Local POS edge core schema — subset of FERN central for offline POS operations.
-- Schema mirrors FERN but uses BIGINT IDs generated by agent Snowflake.

CREATE TABLE IF NOT EXISTS outlet (
  id            BIGINT PRIMARY KEY,
  name          TEXT NOT NULL,
  timezone      TEXT NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_user (
  id            BIGINT PRIMARY KEY,
  username      TEXT UNIQUE NOT NULL,
  display_name  TEXT NOT NULL,
  role          TEXT NOT NULL,
  token_hash    TEXT,              -- cached hashed token for offline relogin
  token_exp_at  TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product (
  id            BIGINT PRIMARY KEY,
  sku           TEXT,
  name          TEXT NOT NULL,
  category_id   BIGINT,
  image_url     TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_product_category ON product(category_id);
CREATE INDEX IF NOT EXISTS ix_product_updated ON product(updated_at DESC);

CREATE TABLE IF NOT EXISTS product_price (
  product_id       BIGINT NOT NULL,
  outlet_id        BIGINT NOT NULL,
  price_cents      BIGINT NOT NULL,
  effective_from   TIMESTAMPTZ NOT NULL,
  effective_to     TIMESTAMPTZ,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (product_id, outlet_id, effective_from)
);

CREATE TABLE IF NOT EXISTS item (
  id            BIGINT PRIMARY KEY,
  sku           TEXT,
  name          TEXT NOT NULL,
  unit          TEXT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_balance (
  item_id          BIGINT NOT NULL,
  outlet_id        BIGINT NOT NULL,
  qty_on_hand      NUMERIC(18, 3) NOT NULL DEFAULT 0,
  last_movement_at TIMESTAMPTZ,
  synced_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (item_id, outlet_id)
);

CREATE TABLE IF NOT EXISTS pos_session (
  id               BIGINT PRIMARY KEY,
  outlet_id        BIGINT NOT NULL,
  manager_id       BIGINT NOT NULL,
  status           TEXT NOT NULL CHECK (status IN ('open', 'closed')),
  business_date    DATE NOT NULL,
  opening_cash     BIGINT NOT NULL DEFAULT 0,
  closing_cash     BIGINT,
  opened_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_pos_session_outlet_status ON pos_session(outlet_id, status);

CREATE TABLE IF NOT EXISTS sale_record (
  id               BIGINT PRIMARY KEY,
  outlet_id        BIGINT NOT NULL,
  pos_session_id   BIGINT NOT NULL REFERENCES pos_session(id),
  cashier_id       BIGINT NOT NULL,
  status           TEXT NOT NULL CHECK (status IN ('draft','submitted','approved','paid','voided','refunded')),
  subtotal_cents   BIGINT NOT NULL,
  discount_cents   BIGINT NOT NULL DEFAULT 0,
  tax_cents        BIGINT NOT NULL DEFAULT 0,
  total_cents      BIGINT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_sale_record_session ON sale_record(pos_session_id);
CREATE INDEX IF NOT EXISTS ix_sale_record_created ON sale_record(created_at DESC);

CREATE TABLE IF NOT EXISTS sale_item (
  id               BIGINT PRIMARY KEY,
  sale_id          BIGINT NOT NULL REFERENCES sale_record(id) ON DELETE CASCADE,
  product_id       BIGINT NOT NULL,
  qty              NUMERIC(18, 3) NOT NULL,
  unit_price_cents BIGINT NOT NULL,
  discount_cents   BIGINT NOT NULL DEFAULT 0,
  line_total_cents BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sale_item_sale ON sale_item(sale_id);

CREATE TABLE IF NOT EXISTS payment (
  id               BIGINT PRIMARY KEY,
  sale_id          BIGINT NOT NULL REFERENCES sale_record(id),
  method           TEXT NOT NULL CHECK (method IN ('cash', 'card', 'qr', 'ewallet')),
  amount_cents     BIGINT NOT NULL,
  state            TEXT NOT NULL DEFAULT 'COMPLETED'
    CHECK (state IN ('PENDING_OFFLINE', 'COMPLETED', 'RECONCILED', 'FAILED')),
  paid_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_payment_sale ON payment(sale_id);

CREATE TABLE IF NOT EXISTS device_meta (
  key              TEXT PRIMARY KEY,
  value            JSONB NOT NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- Seed keys: device_id, worker_id, clock_anchor, catalog_cursor, stock_cursor
