ALTER TABLE app_user
  ADD COLUMN IF NOT EXISTS password_hash TEXT;

ALTER TABLE product
  ADD COLUMN IF NOT EXISTS tax_basis_points BIGINT NOT NULL DEFAULT 0;

ALTER TABLE stock_balance
  ADD COLUMN IF NOT EXISTS qty_reserved_local NUMERIC(18, 3) NOT NULL DEFAULT 0;

ALTER TABLE sale_item
  ADD COLUMN IF NOT EXISTS tax_cents BIGINT NOT NULL DEFAULT 0;
