package com.fern.services.sync.model;

public enum AggregateType {
  PRODUCT,
  CATEGORY,
  MENU,
  PRICE_POLICY,
  PROMOTION,
  TAX_POLICY,
  PAYMENT_METHOD,
  REGION,
  STORE_CONFIG,
  ITEM_AVAILABILITY,
  SALE_ORDER,
  RETURN_ORDER,
  PAYMENT,
  PAYMENT_TRANSACTION,
  KITCHEN_TICKET,
  CASH_SHIFT,
  CASH_MOVEMENT,
  STOCK_MOVEMENT
}
