package com.fern.services.sync.model;

public enum EventType {
  PRODUCT_CREATED,
  PRODUCT_UPDATED,
  CATEGORY_UPDATED,
  MENU_UPDATED,
  PRICE_POLICY_UPDATED,
  PROMOTION_UPDATED,
  TAX_POLICY_UPDATED,
  PAYMENT_METHOD_UPDATED,
  REGION_UPDATED,
  STORE_CONFIG_UPDATED,
  ITEM_AVAILABILITY_UPDATED,
  SALE_ORDER_CREATED,
  SALE_ORDER_CANCELLED,
  RETURN_ORDER_CREATED,
  PAYMENT_CREATED,
  PAYMENT_TRANSACTION_CREATED,
  KITCHEN_TICKET_CREATED,
  KITCHEN_TICKET_UPDATED,
  CASH_SHIFT_CLOSED,
  CASH_MOVEMENT_CREATED,
  STOCK_MOVEMENT_CREATED
}
