FROM maven:3.9.11-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY .mvn .mvn
COPY pom.xml pom.xml
COPY common common
COPY gateway gateway
COPY services services

RUN mvn -pl gateway -am -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /workspace/gateway/target/gateway.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
