FROM maven:3.9.11-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY .mvn .mvn
COPY pom.xml pom.xml
COPY common common
COPY gateway gateway
COPY services services

ARG MODULE_PATH

RUN mvn -pl ${MODULE_PATH} -am -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app

ARG MODULE_PATH

COPY --from=build /workspace/${MODULE_PATH}/target/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
