FROM maven:3.9.11-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY .mvn .mvn
COPY pom.xml pom.xml
COPY common common
COPY gateway gateway
COPY services services
COPY tools tools

RUN mvn -pl gateway -am -DskipTests package && \
    rm -f /workspace/gateway/target/*.jar.original

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /workspace/gateway/target/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
