package com.dorabets.common.spring.auth;

public enum Capability {
  IAM_GOVERNANCE,
  HR_SCHEDULING,
  HR_CONTRACT_CREATE,
  HR_CONTRACT_MANAGE,
  PAYROLL_PREPARE,
  PAYROLL_APPROVE,
  ORG_READ,
  ORG_MUTATE,
  CATALOG_READ,
  CATALOG_MUTATE,
  SALES_READ,
  SALES_WRITE,
  PROCUREMENT_READ,
  PROCUREMENT_WRITE,
  PROCUREMENT_APPROVE,
  INVENTORY_READ,
  INVENTORY_WRITE,
  FINANCE_READ,
  FINANCE_WRITE,
  AUDIT_READ,
  REPORT_READ
}
