"""Central query policy for FERN AI Query.

This package is the source of truth for AI-facing ClickHouse tables, scope
columns, grains, metric definitions, and semantic aliases.
"""

from app.query_policy.policy import (
    ALLOWED_FULL_TABLES,
    ALLOWED_SCHEMAS,
    CODEGEN_TIME_FILTER_REQUIRED_TABLES,
    LOOKUP_ONLY_TABLES,
    METRIC_DEFINITIONS,
    DATA_SOURCE_POLICIES,
    QUERY_DOMAINS,
    TABLE_BLOCKED_SELECT_COLUMNS,
    TABLE_OUTLET_COLUMNS,
    TABLE_POLICIES,
    TABLE_TIME_COLUMNS,
    DataSourcePolicy,
    QueryDomain,
    TablePolicy,
    allowed_tables_for_prompt,
    candidate_tables_for_prompt,
    data_source_policy_rows,
    dataset_for_template,
    datasets_for_template,
    domain_keys_for_question,
    finance_sensitive_tables,
    find_semantic_matches,
    format_domain_contract,
    format_metadata_context,
    get_data_source_policy,
    get_table_policy,
    table_policy_rows,
    tables_for_intent,
)
from app.query_policy.verified_queries import (
    VERIFIED_QUERY_ASSETS,
    VerifiedQueryAsset,
    VerifiedQueryMatch,
    select_verified_query,
)
from app.query_policy.intent_mapping import (
    intent_for_route_and_template,
    intent_for_template,
)
from app.query_policy.learned_scenarios import (
    LearnedScenarioAsset,
    LearnedScenarioMatch,
    SqlWriterScenarioAsset,
    SqlWriterScenarioMatch,
    build_scenario_candidate_from_state,
    build_scenario_key,
    clear_learned_scenarios_cache,
    learned_scenario_rows,
    load_learned_scenarios,
    load_sql_writer_scenarios,
    select_learned_scenario,
    select_sql_writer_scenario,
)
from app.query_policy.semantic_contract import (
    SemanticContractError,
    load_semantic_contracts,
    semantic_contract_by_domain,
    semantic_metric_rows,
)

__all__ = [
    "ALLOWED_FULL_TABLES",
    "ALLOWED_SCHEMAS",
    "CODEGEN_TIME_FILTER_REQUIRED_TABLES",
    "LOOKUP_ONLY_TABLES",
    "METRIC_DEFINITIONS",
    "DATA_SOURCE_POLICIES",
    "QUERY_DOMAINS",
    "TABLE_BLOCKED_SELECT_COLUMNS",
    "TABLE_OUTLET_COLUMNS",
    "TABLE_POLICIES",
    "TABLE_TIME_COLUMNS",
    "DataSourcePolicy",
    "QueryDomain",
    "TablePolicy",
    "allowed_tables_for_prompt",
    "candidate_tables_for_prompt",
    "data_source_policy_rows",
    "dataset_for_template",
    "datasets_for_template",
    "domain_keys_for_question",
    "finance_sensitive_tables",
    "find_semantic_matches",
    "format_domain_contract",
    "format_metadata_context",
    "get_data_source_policy",
    "get_table_policy",
    "table_policy_rows",
    "tables_for_intent",
    "VERIFIED_QUERY_ASSETS",
    "VerifiedQueryAsset",
    "VerifiedQueryMatch",
    "select_verified_query",
    "intent_for_route_and_template",
    "intent_for_template",
    "LearnedScenarioAsset",
    "LearnedScenarioMatch",
    "SqlWriterScenarioAsset",
    "SqlWriterScenarioMatch",
    "build_scenario_candidate_from_state",
    "build_scenario_key",
    "clear_learned_scenarios_cache",
    "learned_scenario_rows",
    "load_learned_scenarios",
    "load_sql_writer_scenarios",
    "select_learned_scenario",
    "select_sql_writer_scenario",
    "SemanticContractError",
    "load_semantic_contracts",
    "semantic_contract_by_domain",
    "semantic_metric_rows",
]
