listen_addresses = '*'
wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = '512MB'
hot_standby = on
shared_preload_libraries = 'pg_stat_statements'
compute_query_id = auto
track_io_timing = on
pg_stat_statements.max = 10000
pg_stat_statements.track = all
pg_stat_statements.save = on
