port 26379
bind 0.0.0.0
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor fern-master redis 6379 2
sentinel down-after-milliseconds fern-master 5000
sentinel failover-timeout fern-master 10000
sentinel parallel-syncs fern-master 1
